# Generated by Django 5.0.2 on 2024-03-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
    ]
