# Generated by Django 5.0.2 on 2024-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('N', 'Not Started'), ('S', 'Stuck'), ('W', 'Working on it'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
