# Generated by Django 5.0.2 on 2024-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='process',
            field=models.CharField(choices=[('S', 'Starting Sprint'), ('D', 'In Design'), ('I', 'In Development'), ('C', 'Continuous Integration')], default='S', max_length=1),
        ),
    ]
