# Generated by Django 5.0.2 on 2024-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='complexity',
            field=models.IntegerField(default=0),
        ),
    ]
