# Generated by Django 5.0.2 on 2024-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='complexity',
            field=models.IntegerField(default=3),
        ),
    ]
